### ISSUE TITLE
how to set default start time 8 AM for each day of calender 

### ISSUE THREAD

**Issue by lokeshguptakiwi** [richardtop/CalendarKit#352] opened 2023-02-22 12:09 UTC

**Comment by richardtop** [comment] 2023-02-22 22:56
Is it a duplicate of #34?

**Comment by lokeshguptakiwi** [comment] 2023-02-23 04:44
No..I want to set 8AM the default start time of calendar for each day. If user want to see above and below time, he can scroll up and down.

**Comment by richardtop** [comment] 2023-02-24 17:10
Would `scrollTo` method of the `dayView` solve your issue? 
https://github.com/richardtop/CalendarKit/blob/master/Sources/DayView.swift#L140

Just try using it like this:

```
dayView.scrollTo(hour24: 8, animated: true/false)
```
Let me know if this is an appropriate solution to your problem

**Comment by lokeshguptakiwi** [comment] 2023-02-25 12:27
yes its work..but when we click on another date ..its automatically shift to 12:00 AM.

**Comment by richardtop** [comment] 2023-02-25 18:08
1. `but when we click on another date ` - this is a limitation of the CalendarKit, as it doesn't preserve the scroll position when you click on the date in the header.  Already reported as #211
2. One workaround would be to invoke the `dayView.scrollTo(hour24: 8, animated: true/false)` method just after `dayView.didMoveToDate` delegate callback: https://github.com/richardtop/CalendarKit/blob/master/Sources/DayViewController.swift#L106 - let me know if this solution works for you.

**Comment by lokeshguptakiwi** [comment] 2023-02-27 04:42
yes, when i try to write scroll code in this method its working.. but their some jerk ...means its first show 12:00 for some millisecond then directly move to 8:00 AM

**Comment by richardtop** [comment] 2023-02-27 10:13
Could you please attach a video? Thanks

**Comment by richardtop** [comment] 2023-02-27 10:43
And the exact code you're using for this? Maybe try using 'willMoveTo' instead of 'didMoveTo'? Let me know if there is any difference.
If this doesn't help, I'll convert this ticket to an enhancement.

**Comment by lokeshguptakiwi** [comment] 2023-02-27 10:51
No , when i move that line to willMoveTo..then nothing are happing.

**Comment by richardtop** [comment] 2023-02-27 11:06
And do you use `animated:false`?

**Comment by lokeshguptakiwi** [comment] 2023-02-27 11:12
yes on didMoveTo and same on willMoveTo.

**Comment by richardtop** [comment] 2023-02-27 12:18
Ok, I've changed this to enhancement. Would you be willing to make relevant changes to the CalendarKit to implement this feature?

I can briefly explain how to achieve this functionality.

**Comment by lokeshguptakiwi** [comment] 2023-02-27 12:41
yes if you will help me..i will make changes.

**Comment by lokeshguptakiwi** [comment] 2023-02-28 04:54
oky..let me check this one..Thanks

**Comment by richardtop** [comment] 2023-02-28 06:59
Please keep me updated on whether you resolve this issue either by my suggestion or by any other means...

**Closed** 2023-03-10 14:27 UTC
Labels: enhancement
