### ISSUE TITLE
Moving to date in viewDidLoad causes date to skip

### ISSUE THREAD

**Issue by raguiar2** [richardtop/CalendarKit#182] opened 2018-11-17 22:04 UTC
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
I want to call move(to:) in viewDidLoad so I can load the DayViewController on a certian date, but if I do this, it causes some odd behavior. 

When I swipe right or left on the calendarkit view after calling move(to:) in viewDidLoad, the calendar jumps forward/backward two days instead of one. For example, swiping backwards would move me to November 15th if the date i jump to is November 17th. 

I tried putting the method in viewDidAppear, but if I do that, the calendar loads and then awkwardly jumps to the specified date. I'd like it to open to the specified date and not skip days when swiping back and forth. 

##### Code I'm using with CalendarKit

```Swift

override func viewDidLoad() {
  super.viewDidLoad()
  self.dayView.state?.move(to: selectedDate)
  dayView.autoScrollToFirstEvent = true
  reloadData()
}

```

#### Result I am trying to achieve

I would like to be able to load the calendar to a certain date, and have it work normally from there.

**Comment by richardtop** [comment] 2018-11-18 19:15
A few suggestions:
1. Try executing this logic in `viewWillAppear`
2. Try `custom-calendar` branch and see if the issue still persists.

**Comment by richardtop** [comment] 2018-11-18 19:41
@raguiar2 thanks for the report, its definitely a bug and I'll get back to it.

**Comment by prafulargiddi** [comment] 2018-12-11 09:53
i have facing same problem please try to solve it.

**Comment by prafulargiddi** [comment] 2018-12-11 11:10
> I tried both of those, but it doesn't seem to work. The closest hack I can do is put it in `viewDidAppear`, but then it visibly moves to the date after the view has transitioned.

Hi are you get the solution for the same?

**Comment by MinseokJeong** [comment] 2019-02-13 09:33
Hmm I have facing same situation. Anybody please fix these issue please :D

**Comment by keith-williams2** [comment] 2019-04-26 13:44
I solved this by adding a function to the DayViewStateUpdating protocol called moveWithoutAnimation(to date: Date).  I then added my own implementation of this and called it in the viewDidLoad().  If I were to spend more time on this I would probably change the move function to public func move(from oldDate: Date, to newDate: Date, _ animated: Bool = true)

**Comment by richardtop** [comment] 2020-04-18 19:36
Closing, as the issue is resolved in the latest CalendarKit version.

**Closed by richardtop** 2020-04-18 19:36 UTC
Labels: bug
