### ISSUE TITLE
How can you do so that the hours between one event and another do not collide?

### ISSUE THREAD

**Issue by Bodgar** [richardtop/CalendarKit#118] opened 2017-12-08 18:29 UTC
How can you do so that the hours between one event and another do not collide?

**Comment by richardtop** [comment] 2017-12-25 10:40
Hi @Bodgar,
could you please explain, what you're trying to achieve in more details, or add some screenshots/mockups?

**Comment by richardtop** [comment] 2017-12-28 19:08
Closing this issue, feel free to open a new one if the problem is still relevant.

**Closed by richardtop** 2017-12-28 19:08 UTC
Labels: question
