### ISSUE TITLE
If the particular slot has already booked then how to disable that hourly slot

### ISSUE THREAD

**Issue by pks297** [richardtop/CalendarKit#252] opened 2020-04-03 05:19 UTC
### New Issue Checklist
If the particular slot has already booked then how to disable that hourly slot, the **user can not click on that particular booked slot**.

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment] 2020-04-13 22:44
Duplicate of  #249

**Closed by richardtop** 2020-04-13 22:44 UTC
