### ISSUE TITLE
EventView in resize mode scrolls to other timelines

### ISSUE THREAD

**Issue by RareScrap** [richardtop/CalendarKit#276] opened 2020-10-21 04:12 UTC
### New Issue Checklist

- [x] Use the latest version of CalendarKit (v0.13.13)
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
When a long click was made and the view switched to resize mode - it does not remain on its own timeline when you swipe to left or right. The EventView disappears after another timeline has been tapped. The bug is also present in the demo project. [Here's a video](https://youtu.be/85NRCEk5CAM) demonstrated the bug.

**Comment by richardtop** [comment] 2020-10-23 14:59
It's a known issue. Stop editing the event programmatically as the user begins to scroll the calendar.
Currently, it's not supported to drag the edited event to the other day.

This is not a bug, but rather an incorrect library integration. Feel free to close this issue if the suggested approach resolves it.

**Comment by RareScrap** [comment] 2020-11-16 10:04
Done in #287.

**Closed** 2020-11-16 19:15 UTC
