### ISSUE TITLE
Limit the hours?

### ISSUE THREAD

**Issue by Bodgar** [richardtop/CalendarKit#131] opened 2018-01-10 19:15 UTC
How can I limit the hours that appear in the calendar? for example that instead of being from 00:00 to 00:00 it is from 07:00 to 20:00

**Comment by richardtop** [comment] 2018-01-10 20:19
A duplicate of #34.
Please, take a look at #126 and #122, maybe that approach will suit your needs.

**Closed by richardtop** 2018-01-10 20:19 UTC
