### ISSUE TITLE
Wrong layout when dayView is not full size

### ISSUE THREAD

**Issue by diegorozen** [richardtop/CalendarKit#25] opened 2017-02-25 19:48 UTC
Attaching snapshot and sample code adapted from demo one

![simulator screen shot feb 25 2017 2 47 40 pm](https://cloud.githubusercontent.com/assets/235824/23334280/64f29052-fb69-11e6-91ec-289c965a2c73.png)

[ExampleController.swift.zip](https://github.com/richardtop/CalendarKit/files/801450/ExampleController.swift.zip)

**Comment by richardtop** [comment] 2017-02-25 20:02
Hi, @diegorozen,
the problem is in references to `UIScreen.main.bounds` in some files. Right now, there are three such files. This is incorrect and should be fixed, because of two cases:
1. The one you've pointed out right now (when `UIScreen.main.bounds != view.bounds`
2. When `UIScreen.main.bounds != window.bounds`, e.g. if using iPad multitasking.

**Comment by diegorozen** [comment] 2017-02-25 20:13
Right using self.bounds instead for UIScreen bounds and moving the lines to layoutSubviews fixes the issue

**Comment by richardtop** [comment] 2017-02-25 21:49
Fixed in #26

**Closed by richardtop** 2017-02-25 21:49 UTC
Labels: bug

**Comment by avinash-ramireddy** [comment] 2019-02-15 05:31
I have also issues with this.
I just demo project(CalendarKit) from this github repo.

When we rotate to landscape and comeback then 
1. DayHeaderView view day and date are not aligned properly.
<img width="332" alt="screenshot 2019-02-15 at 10 59 50 am" src="https://user-images.githubusercontent.com/16798757/52836521-eef85280-3110-11e9-915a-3f33f840b0b2.png">

2. TimelinePagerView timeline view became scrollable instead of going to next date.
<img width="387" alt="screenshot 2019-02-15 at 11 00 21 am" src="https://user-images.githubusercontent.com/16798757/52836529-f586ca00-3110-11e9-9b05-6d3803a971d2.png">

Look at bottom of screen. There is scrollbar added.
