### ISSUE TITLE
How can I use calendarkit in the new swiftui

### ISSUE THREAD

**Issue by Pamposgsk** [richardtop/CalendarKit#328] opened 2022-01-16 20:52 UTC
Hi,
Thanks for this great package.
Could you please explain how can I use this package With latest SwiftUI ?
Thanks
Pampos

**Comment by richardtop** [comment] 2022-01-16 20:58
Please refer to this StackOverflow question: https://stackoverflow.com/questions/64432749/can-i-use-view-controller-calendarkit-in-swiftui-application

This is a duplicate of #270

**Closed by richardtop** 2022-01-16 20:58 UTC
Labels: question
