### ISSUE TITLE
Need help to create Calendar for week View Or Three day View. Could you please let me know how can I do that?

### ISSUE THREAD

**Issue by SuyogCTS** [richardtop/CalendarKit#231] opened 2019-11-15 11:46 UTC
### New Issue Checklist

- [ ] Use the latest version of CalendarKit
- [ ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment] 2019-11-15 13:01
Hi, currently this is not supported.
It's a duplicate of #22. 
You may, however, try to integrate multiple CalendarKit components and assemble a week-view - like design.
I think that the proper implementation of the Week View would require changes in the underlying CalendarKit modules.

**Closed** 2019-11-17 23:57 UTC
Labels: enhancement, question
